# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joinus', '0001_initial'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_url', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=15)),
                ('scores_achieved', models.CharField(max_length=6)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.student')),
            ],
        ),
        migrations.CreateModel(
            name='course_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_main_content_id', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=3)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
                ('course_sub_content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.coursecontent')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.student')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=5)),
                ('review', models.CharField(max_length=250)),
                ('status', models.CharField(default='active', max_length=100)),
                ('flag', models.CharField(default='n', max_length=2)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.student')),
            ],
        ),
        migrations.CreateModel(
            name='submissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(max_length=6)),
                ('no_of_questions', models.CharField(max_length=3)),
                ('submission_date', models.CharField(max_length=15)),
                ('submission_time', models.CharField(max_length=15)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.quiz')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.student')),
            ],
        ),
    ]
