# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joinus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('question_type', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=200)),
                ('feedbackc', models.CharField(max_length=200)),
                ('feedbackw', models.CharField(max_length=200)),
                ('hint', models.CharField(max_length=200)),
                ('option1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('option2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('option3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('option4', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('Adate', models.CharField(max_length=50)),
                ('Atime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
                ('cdesc', models.CharField(default='none', max_length=500)),
                ('taughtby', models.CharField(max_length=50)),
                ('prerequisite', models.CharField(max_length=200)),
                ('course_language', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('fee', models.IntegerField(default=0)),
                ('start_date', models.CharField(max_length=12)),
                ('end_date', models.CharField(max_length=12)),
                ('lock', models.CharField(default=0, max_length=1)),
                ('hide', models.CharField(default=0, max_length=1)),
                ('course_pic', models.FileField(default='abc.jpg', upload_to='')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.categories')),
                ('creatorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='coursecontent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_sub_id', models.IntegerField(default=0)),
                ('content_name', models.CharField(max_length=50)),
                ('content_description', models.CharField(default='description', max_length=500)),
                ('content_type', models.CharField(default='null', max_length=10)),
                ('content_url', models.FileField(default='abc.mp4', upload_to='')),
                ('content_sequence_no', models.IntegerField(default=-1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
            ],
        ),
        migrations.CreateModel(
            name='difficulty_levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='enrolldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.CharField(default='2017-09-16 13:18:37.283604', max_length=200)),
                ('fee_status', models.CharField(default='n', max_length=1)),
                ('course_progress', models.CharField(default='0', max_length=10)),
                ('flag', models.CharField(default='0', max_length=1)),
                ('progress_data', models.CharField(default='', max_length=1000)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.student')),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(max_length=100)),
                ('faq_answer', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
            ],
        ),
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=400)),
                ('quiz_title', models.CharField(max_length=50)),
                ('quiz_description', models.CharField(max_length=500)),
                ('quiz_duration', models.IntegerField()),
                ('quiz_weightage', models.CharField(max_length=4)),
                ('quiz_date', models.CharField(max_length=100)),
                ('lock', models.CharField(max_length=1)),
                ('hide', models.CharField(max_length=1)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.coursecontent')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.difficulty_levels')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='resource_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='resources1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='none', max_length=500)),
                ('content_url1', models.FileField(default='xyz.mp4', upload_to='')),
                ('content_url2', models.CharField(default='', max_length=200)),
                ('sequence_no', models.IntegerField(default=-1)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.coursecontent')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.resource_type')),
            ],
        ),
        migrations.CreateModel(
            name='uploadcsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csvfile', models.FileField(default='abc.csv', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='announcements',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        ),
        migrations.AddField(
            model_name='add_question',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course'),
        ),
        migrations.AddField(
            model_name='add_question',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.difficulty_levels'),
        ),
    ]
