# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joinus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_sub_id', models.CharField(default=0, max_length=10)),
                ('blog_name', models.CharField(max_length=100)),
                ('post_title', models.CharField(max_length=100)),
                ('post_description', models.TextField(max_length=5000)),
                ('date', models.CharField(default='16/09/2017', max_length=15)),
                ('time', models.CharField(default='13:18', max_length=15)),
                ('count', models.CharField(default=0, max_length=15)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.student')),
            ],
        ),
    ]
