# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('joinus', '0001_initial'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='askquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_subid', models.IntegerField(default=0)),
                ('question_heading', models.CharField(max_length=100)),
                ('question_description', models.TextField(max_length=250)),
                ('reply_description', models.CharField(max_length=250)),
                ('sequence_no', models.CharField(max_length=5)),
                ('question_date', models.CharField(default='16/09/2017', max_length=20)),
                ('question_time', models.CharField(default='13:18', max_length=20)),
                ('reply_date', models.CharField(default='16/09/2017', max_length=20)),
                ('reply_time', models.CharField(default='13:18', max_length=20)),
                ('question_flag', models.CharField(default='y', max_length=1)),
                ('reply_flag', models.CharField(default='n', max_length=1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.course')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.instructor')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joinus.student')),
            ],
        ),
    ]
